---
- name: Deploy a guest from a template
  hosts: localhost
  vars:
    vcenter_hostname: 192.168.110.11
    vcenter_username: administrator
    vcenter_password: P@ssw0rd 
    v_name: iqbal-joindomain
    v_template: windowtemplate
    v_datastore:  ESXi_Datastore_VM0
  tasks:
  - name: Create a virtual machine from a template
    vmware_guest:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: no
      datacenter: vcenter6
      cluster: cluster
      folder: /
      name: "{{ v_name }}"
      template: "{{ v_template }}"
      state:  poweredon
      disk:
      - size_gb:  40
        type: thin
        datastore:  "{{ v_datastore }}"
      networks:
      - name: DPortGroup-vlan30 
        ip: 192.168.110.74
        netmask:  255.255.255.0
        gateway:  192.168.110.254
        domain: asia.com
        dns_servers:
        - 192.168.110.186
      customization:
        joindomain: asia.com
        domainadmin: administrator
        domainadminpassword: P@ssw0rd
        autologon:  yes
        dns_servers:
        - 192.168.110.186
        domain: asia.com
        password: P@ssw0rd!
        runonce:
        - powershell.exe  -ExecutionPolicy Unrestricted -File C:\ConfigureRemotingForAnsible.ps1 -ForceNewSSLCert -EnableCredSSP
    delegate_to: localhost
    register: deploy

